"""Add messages table for private messaging

Revision ID: 8ac33689406c
Revises: ede0ab3d80d0
Create Date: 2026-02-11 10:24:30.083984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac33689406c'
down_revision = 'ede0ab3d80d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_receiver_messages', ['receiver_id', 'created_at'], unique=False)
        batch_op.create_index('idx_sender_messages', ['sender_id', 'created_at'], unique=False)
        batch_op.create_index('idx_unread_messages', ['receiver_id', 'is_read'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_unread_messages')
        batch_op.drop_index('idx_sender_messages')
        batch_op.drop_index('idx_receiver_messages')

    op.drop_table('messages')
    # ### end Alembic commands ###
